module App exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (..)


main =
    div []
        [ section [ class "hero is-info is-medium is-bold" ]
            [ div [ class "hero-head" ]
                [ nav [ class "navbar" ]
                    [ div [ class "container " ]
                        [ div [ class "navbar-brand" ]
                            [ a [ class "navbar-item", href "http://skynetng.pw" ] [ span [] [ text "CloudX" ] ]
                            , span [ class "navbar-burger burger", attribute "data-target" "navbarMenu" ]
                                [ span [] []
                                , span [] []
                                , span [] []
                                ]
                            ]
                        , div [ id "navbarMenu", class "navbar-menu" ]
                            [ div [ class "navbar-end" ]
                                [ a [ class "navbar-item is-active" ] [ text "Serverless" ]
                                , a [ class "navbar-item" ] [ text "Cloud" ]
                                , a [ class "navbar-item" ] [ text "On premises" ]
                                , a [ class "navbar-item" ] [ text "Contact" ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        , section [ class "hero is-info is-medium is-bold" ]
            [ div [ class "hero-body" ]
                [ div [ class "container has-text-centered" ]
                    [ h1 [ class "title" ]
                        [ text "Cloud and serverless it's the future, let us show you how..." ]
                    , h2
                        [ class "subtitle" ]
                        [ text "As you should be aware by now, having your own hardware and keeping everything in your offices can bring a lot of pain and increased costs against all the options that the cloud can offer." ]
                    ]
                ]
            ]
        , div [ class "box cta" ]
            [ p [ class "has-text-centered" ]
                [ span [ class "tag is-primary" ] [ text "New" ]
                , text "Serverless framework can help you reduce hosting costs and scalability issues."
                ]
            ]
        , section
            [ class "container" ]
            [ div [ class "columns features" ]
                [ div [ class "column is-4" ]
                    [ div [ class "card" ]
                        [ div [ class "card-image has-text-centered" ]
                            [ i [ class "fa fab fa-cloudscale" ] []
                            ]
                        , div [ class "card-content" ]
                            [ div [ class "content" ]
                                [ h4 [] [ text "Scalability" ]
                                , p []
                                    [ text "Serverless backends expand and contract with demand. Go get on the front page of HackerNews, we dare you." ]
                                , p
                                    []
                                    [ a [ href "/contact" ] [ text "Be serverless" ] ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "column is-4" ]
                    [ div [ class "card" ]
                        [ div [ class "card-image has-text-centered" ]
                            [ i [ class "fas fa-fighter-jet" ] []
                            ]
                        , div [ class "card-content" ]
                            [ div [ class "content" ]
                                [ h4 [] [ text "Lifecycle" ]
                                , p []
                                    [ text "Serverless cuts weeks off development cycles. Don’t spend time provisioning unused infrastructure." ]
                                , p
                                    []
                                    [ a [ href "/contact" ] [ text "Be serverless" ] ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "column is-4" ]
                    [ div [ class "card" ]
                        [ div [ class "card-image has-text-centered" ]
                            [ i [ class "fas fa-fighter-jet" ] []
                            ]
                        , div [ class "card-content" ]
                            [ div [ class "content" ]
                                [ h4 [] [ text "Save money" ]
                                , p []
                                    [ text "Build, test and deploy cloud functions to any provider. Skip the setup; deploy your function right now and only pay for what you really use." ]
                                , p
                                    []
                                    [ a [ href "/contact" ] [ text "Be serverless" ] ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        , div
            [ class "container" ]
            [ h2 [ class "title" ] [ text "Perfect for developers" ]
            , p [ class "subtitle" ] [ text "Serverless Framework is your single toolkit for deploying serverless architectures to any provider. You build the features, we configure the infrastructure. Done." ]
            , br [] []
            , h2 [ class "title" ] [ text "Serverless" ]
            , p [ class "subtitle" ] [ text "You can pick your preferred cloud provider: Amazon AWS, Google Cloud, Microsoft Azure, IBM OpenWhisk." ]
            , br [] []
            , h2 [ class "title" ] [ text "Cloud" ]
            , p [ class "subtitle" ] [ text "You can get vps/vpc/etc and let us do the administration: Amazon AWS, Google Cloud, Microsoft Azure, IBM OpenWhisk." ]
            , br [] []
            , h2 [ class "title" ] [ text "On premises" ]
            , p [ class "subtitle" ] [ text "You can still use your hardware and let us do the administration" ]
            ]
        ]
